import { 
  WebsiteProfile, 
  SocialLink, 
  HeroMedia, 
  InternalApplication, 
  OfficialReportingApp, 
  AppUser 
} from '../types/database';

export const INITIAL_WEBSITE_PROFILE: WebsiteProfile = {
  id: 'profile-rsud-almulk-001',
  hospital_name: 'RSUD Al-Mulk Kota Sukabumi',
  tagline: 'Satu Pintu Menuju Ekosistem Digital RSUD Al-Mulk',
  description: 'Satu Pintu Menuju Ekosistem Digital RSUD Al-Mulk - Portal terpusat akses seluruh aplikasi operasional internal rumah sakit dan sistem pelaporan resmi pemerintah.',
  logo_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=300&auto=format&fit=crop&q=80',
  address: 'Jl. Pelabuhan II No. 175, Cikondang, Kec. Citamiang, Kota Sukabumi, Jawa Barat 43142',
  phone: '(0266) 243224',
  emergency_phone: '(0266) 243225 / IGD 24 Jam',
  email: 'info@rsudalmulk.sukabumikota.go.id',
  website_url: 'https://rsudalmulk.sukabumikota.go.id',
  service_hours: 'IGD & Rawat Inap: 24 Jam | Rawat Jalan: Senin - Sabtu (07.30 - 14.00 WIB)',
  updated_at: new Date().toISOString()
};

export const INITIAL_PROFILE = INITIAL_WEBSITE_PROFILE;


export const INITIAL_SOCIAL_LINKS: SocialLink[] = [
  {
    id: 'soc-1',
    platform: 'instagram',
    title: 'Instagram Resmi',
    url: 'https://instagram.com/rsud_almulk_kotasukabumi',
    icon: 'Instagram',
    is_active: true,
    display_order: 1
  },
  {
    id: 'soc-2',
    platform: 'facebook',
    title: 'Facebook Fanpage',
    url: 'https://facebook.com/rsudalmulkkotasukabumi',
    icon: 'Facebook',
    is_active: true,
    display_order: 2
  },
  {
    id: 'soc-3',
    platform: 'youtube',
    title: 'YouTube Channel',
    url: 'https://youtube.com/@rsudalmulkofficial',
    icon: 'Youtube',
    is_active: true,
    display_order: 3
  },
  {
    id: 'soc-4',
    platform: 'tiktok',
    title: 'TikTok Edukasi Kesehatan',
    url: 'https://tiktok.com/@rsudalmulk',
    icon: 'Video',
    is_active: true,
    display_order: 4
  },
  {
    id: 'soc-5',
    platform: 'whatsapp',
    title: 'Layanan Informasi & Pengaduan (WhatsApp)',
    url: 'https://wa.me/6281234567890',
    icon: 'MessageCircle',
    is_active: true,
    display_order: 5
  },
  {
    id: 'soc-6',
    platform: 'website',
    title: 'Portal Utama RSUD Al-Mulk',
    url: 'https://rsudalmulk.sukabumikota.go.id',
    icon: 'Globe',
    is_active: true,
    display_order: 6
  }
];

export const INITIAL_HERO_MEDIA: HeroMedia[] = [
  {
    id: 'hero-1',
    title: 'Gedung Pelayanan Terpadu RSUD Al-Mulk',
    description: 'Fasilitas kesehatan modern dan humanis untuk masyarakat Kota Sukabumi dan sekitarnya.',
    media_type: 'image',
    media_url: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=1920&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=300&auto=format&fit=crop&q=80',
    display_order: 1,
    is_active: true,
    overlay_opacity: 65,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'hero-2',
    title: 'Pelayanan Medis & Laboratorium Canggih',
    description: 'Transformasi digital kesehatan untuk percepatan penegakan diagnosis dan efisiensi pelaporan.',
    media_type: 'image',
    media_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=1920&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=300&auto=format&fit=crop&q=80',
    display_order: 2,
    is_active: true,
    overlay_opacity: 70,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'hero-3',
    title: 'Digitalisasi Rumah Sakit RSUD Al-Mulk',
    description: 'Integrasi penuh rekam medis elektronik (RME) dan ekosistem satu data kesehatan.',
    media_type: 'image',
    media_url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1920&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=300&auto=format&fit=crop&q=80',
    display_order: 3,
    is_active: true,
    overlay_opacity: 65,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const INITIAL_INTERNAL_APPS: InternalApplication[] = [
  {
    id: 'app-int-1',
    name: 'SIPAKAR',
    slug: 'sipakar',
    description: 'Sistem Pelaporan Kinerja Seksi Penunjang Rumah Sakit untuk monitoring dan evaluasi layanan penunjang medis & non-medis.',
    logo_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://sipakar.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Penunjang',
    unit: 'Seksi Penunjang RS',
    status: 'aktif',
    display_order: 1,
    is_featured: true,
    click_count: 342,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-2',
    name: 'SIMRS Khanza Al-Mulk',
    slug: 'simrs-khanza-almulk',
    description: 'Sistem Informasi Manajemen Rumah Sakit Utama (SIMRS) mencakup Rawat Jalan, Rawat Inap, IGD, Radiologi, Laboratorium, dan Billing.',
    logo_url: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://simrs.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Medis dan Keperawatan',
    unit: 'Instalasi TI & SIMRS',
    status: 'aktif',
    display_order: 2,
    is_featured: true,
    click_count: 512,
    created_at: '2025-01-05T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-3',
    name: 'E-RESEP & FARMASI DIGITAL',
    slug: 'e-resep-farmasi-digital',
    description: 'Modul resep elektronik terpadu dokter, telaah obat apoteker, dan monitoring ketersediaan obat depo farmasi secara real-time.',
    logo_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://farmasi.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Penunjang',
    unit: 'Instalasi Farmasi',
    status: 'aktif',
    display_order: 3,
    is_featured: false,
    click_count: 289,
    created_at: '2025-01-15T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-4',
    name: 'SI-MUTU AL-MULK',
    slug: 'si-mutu-almulk',
    description: 'Sistem Pengukuran & Pelaporan Indikator Mutu Nasional (INM) dan Indikator Mutu Unit Kerja RSUD Al-Mulk.',
    logo_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://mutu.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Medis dan Keperawatan',
    unit: 'Komite Mutu & Keselamatan Pasien',
    status: 'aktif',
    display_order: 4,
    is_featured: false,
    click_count: 178,
    created_at: '2025-01-20T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-5',
    name: 'SI-KEP RSAM (Kepegawaian)',
    slug: 'si-kep-rsam',
    description: 'Sistem Informasi Kepegawaian, Presensi Digital Geotagging, Logbook Harian Pegawai, dan Manajemen Cuti ASN & Non-ASN.',
    logo_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://kepegawaian.rsudalmulk.sukabumikota.go.id',
    category: 'Penatausahaan, Kepegawaian, Perencanaan, dan Keuangan',
    unit: 'Subbag Kepegawaian & Tata Usaha',
    status: 'aktif',
    display_order: 5,
    is_featured: false,
    click_count: 420,
    created_at: '2025-01-12T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-6',
    name: 'E-LOGISTIK & BMHP',
    slug: 'e-logistik-bmhp',
    description: 'Pengelolaan stok persediaan barang farmasi, bahan medis habis pakai (BMHP), dan inventaris barang non-medis.',
    logo_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://logistik.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Penunjang',
    unit: 'Gudang Farmasi & Logistik',
    status: 'aktif',
    display_order: 6,
    is_featured: false,
    click_count: 145,
    created_at: '2025-02-01T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-7',
    name: 'LAPOR-MULK (SI-ADU)',
    slug: 'lapor-mulk-si-adu',
    description: 'Portal Pelayanan dan Pengaduan Pasien / Masyarakat Terpadu RSUD Al-Mulk untuk respon cepat komplain dan survei kepuasan.',
    logo_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://pengaduan.rsudalmulk.sukabumikota.go.id',
    category: 'Penatausahaan, Kepegawaian, Perencanaan, dan Keuangan',
    unit: 'Humas & Pengaduan',
    status: 'aktif',
    display_order: 7,
    is_featured: false,
    click_count: 198,
    created_at: '2025-02-05T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-8',
    name: 'SI-BED REALTIME AL-MULK',
    slug: 'si-bed-realtime',
    description: 'Dashboard informasi ketersediaan tempat tidur (bed occupancy rate) ruang rawat inap dan isolasi secara realtime.',
    logo_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://bed.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Medis dan Keperawatan',
    unit: 'Admission & Rawat Inap',
    status: 'aktif',
    display_order: 8,
    is_featured: false,
    click_count: 310,
    created_at: '2025-02-10T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-9',
    name: 'E-SURAT & ARSIP DINAS',
    slug: 'e-surat-arsip-dinas',
    description: 'Aplikasi pengelolaan naskah dinas elektronik, penomoran surat otomatis, disposisi digital pimpinan, dan kearsipan.',
    logo_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://surat.rsudalmulk.sukabumikota.go.id',
    category: 'Penatausahaan, Kepegawaian, Perencanaan, dan Keuangan',
    unit: 'Bagian Tata Usaha',
    status: 'aktif',
    display_order: 9,
    is_featured: false,
    click_count: 165,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-int-10',
    name: 'SIP-JALAN (Daftar Pasien)',
    slug: 'sip-jalan-daftar-online',
    description: 'Sistem Informasi Pendaftaran Online Pasien Poliklinik Rawat Jalan dan Anjungan Pasien Mandiri (APM).',
    logo_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://daftar.rsudalmulk.sukabumikota.go.id',
    category: 'Pelayanan Medis dan Keperawatan',
    unit: 'Instalasi Rawat Jalan',
    status: 'aktif',
    display_order: 10,
    is_featured: false,
    click_count: 489,
    created_at: '2025-02-14T08:00:00Z',
    updated_at: new Date().toISOString()
  }
];

export const INITIAL_OFFICIAL_APPS: OfficialReportingApp[] = [
  {
    id: 'app-off-1',
    name: 'SIRS Online (R1 - R5 Kemenkes)',
    slug: 'sirs-online-kemenkes',
    description: 'Sistem Informasi Rumah Sakit Kemenkes RI untuk pelaporan data dasar, ketenagaan, fasilitas tempat tidur, dan morbiditas/mortalitas pasien.',
    logo_url: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://sirs.kemkes.go.id',
    institution: 'Kementerian Kesehatan RI',
    category: 'Pelaporan Rutin',
    status: 'aktif',
    display_order: 1,
    is_featured: true,
    click_count: 388,
    created_at: '2025-01-01T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-2',
    name: 'SISRUTE (Rujukan Terintegrasi)',
    slug: 'sisrute-kemenkes',
    description: 'Sistem Informasi Rujukan Terintegrasi berbasis internet yang menghubungkan data pasien dari tingkat pertama ke tingkat lanjutan dan antar faskes.',
    logo_url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://sisrute.kemkes.go.id',
    institution: 'Kementerian Kesehatan RI',
    category: 'Rujukan & Transfer',
    status: 'aktif',
    display_order: 2,
    is_featured: true,
    click_count: 412,
    created_at: '2025-01-02T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-3',
    name: 'BPJS V-Claim & SEP',
    slug: 'bpjs-vclaim-sep',
    description: 'Aplikasi Penerbitan Surat Eligibilitas Peserta (SEP) dan verifikasi klaim BPJS Kesehatan secara daring untuk pasien rawat jalan & inap.',
    logo_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://vclaim.bpjs-kesehatan.go.id',
    institution: 'BPJS Kesehatan',
    category: 'JKN & Klaim',
    status: 'aktif',
    display_order: 3,
    is_featured: true,
    click_count: 670,
    created_at: '2025-01-03T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-4',
    name: 'ASPAK Kemenkes',
    slug: 'aspak-kemenkes',
    description: 'Aplikasi Sarana, Prasarana dan Alat Kesehatan untuk pemetaan fasilitas dan kelayakan izin operasional rumah sakit.',
    logo_url: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://aspak.kemkes.go.id',
    institution: 'Kementerian Kesehatan RI',
    category: 'Sarana & Alkes',
    status: 'aktif',
    display_order: 4,
    is_featured: false,
    click_count: 215,
    created_at: '2025-01-04T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-5',
    name: 'E-Klaim INA-CBGs',
    slug: 'e-klaim-ina-cbgs',
    description: 'Sistem pengelompokan tarif pelayanan kesehatan berbasis casemix untuk penagihan pembiayaan Jaminan Kesehatan Nasional.',
    logo_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://inacbg.kemkes.go.id',
    institution: 'Kementerian Kesehatan RI',
    category: 'JKN & Klaim',
    status: 'aktif',
    display_order: 5,
    is_featured: false,
    click_count: 340,
    created_at: '2025-01-05T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-6',
    name: 'SPGDT 119 Kota Sukabumi',
    slug: 'spgdt-119-sukabumi',
    description: 'Sistem Penanggulangan Gawat Darurat Terpadu Dinas Kesehatan Kota Sukabumi untuk koordinasi ambulans dan penanganan darurat pra-faskes.',
    logo_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://spgdt.sukabumikota.go.id',
    institution: 'Dinas Kesehatan Kota Sukabumi',
    category: 'Kegawatdaruratan',
    status: 'aktif',
    display_order: 6,
    is_featured: false,
    click_count: 185,
    created_at: '2025-01-06T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-7',
    name: 'SKDR Jabar (Kewaspadaan Dini)',
    slug: 'skdr-dinkes-jabar',
    description: 'Sistem Kewaspadaan Dini dan Respon Penyakit Berpotensi KLB (Kejadian Luar Biasa) Dinas Kesehatan Provinsi Jawa Barat.',
    logo_url: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://skdr.surveilans.org',
    institution: 'Dinas Kesehatan Provinsi Jawa Barat',
    category: 'Surveilans Penyakit',
    status: 'aktif',
    display_order: 7,
    is_featured: false,
    click_count: 132,
    created_at: '2025-01-07T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-8',
    name: 'HFIS BPJS Kesehatan',
    slug: 'hfis-bpjs-kesehatan',
    description: 'Health Facilities Information System untuk profil faskes, updating dokter spesialis, jadwal poli, dan sarana kredensialing BPJS.',
    logo_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://hfis.bpjs-kesehatan.go.id',
    institution: 'BPJS Kesehatan',
    category: 'Kredensialing & Profil',
    status: 'aktif',
    display_order: 8,
    is_featured: false,
    click_count: 220,
    created_at: '2025-01-08T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-9',
    name: 'SATUSEHAT Kemenkes RI',
    slug: 'satusehat-kemenkes',
    description: 'Platform integrasi data rekam medis elektronik (RME) faskes dengan Ekosistem Satu Data Kesehatan Nasional Kementerian Kesehatan RI.',
    logo_url: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://satusehat.kemkes.go.id',
    institution: 'Kementerian Kesehatan RI',
    category: 'Integrasi RME Nasional',
    status: 'aktif',
    display_order: 9,
    is_featured: true,
    click_count: 530,
    created_at: '2025-01-09T08:00:00Z',
    updated_at: new Date().toISOString()
  },
  {
    id: 'app-off-10',
    name: 'SIASN BKN',
    slug: 'siasn-bkn',
    description: 'Sistem Informasi Aparatur Sipil Negara Badan Kepegawaian Negara untuk kenaikan pangkat, mutasi, dan pensiun pegawai RSUD Al-Mulk.',
    logo_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&auto=format&fit=crop&q=80',
    app_url: 'https://siasn.bkn.go.id',
    institution: 'Kementerian / Lembaga Lain',
    category: 'Kepegawaian Negara',
    status: 'aktif',
    display_order: 10,
    is_featured: false,
    click_count: 195,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: new Date().toISOString()
  }
];

export const INITIAL_ADMIN_USERS: AppUser[] = [
  {
    id: 'usr-admin-1',
    email: 'admin.rsam@sukabumikota.go.id',
    name: 'Administrator Portal RSAM',
    role: 'superadmin',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    id: 'usr-admin-2',
    email: 'penunjangrsam@gmail.com',
    name: 'Seksi Penunjang RSUD Al-Mulk',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: '2025-01-02T00:00:00Z',
    updated_at: '2025-01-02T00:00:00Z'
  }
];
